// Generated by https://quicktype.io

import type { Company } from "./company";

export interface Deal {
  id: number;
  company_id: number;
  name: string;
  description: string;
  image_url: string;
  created_at: null;
  updated_at: null;
  company: Company;
}
