// Generated by https://quicktype.io

import type { Location } from "./tour";
import type { Company, User } from "./user";

export interface Offer {
  id: number;
  company_tour_id: number;
  starts_at: Date;
  ends_at: Date;
  hourly_rate_eur_cents: number;
  external_id: string;
  cancelled_at: Date | null;
  created_at: Date;
  updated_at: Date;
  laravel_through_key: number;
  tour: Tour;
  assigned_company_resources: AssignedCompanyResource[];
  assigned_guides: AssignedGuide[];
  pax: Pax[];
  total_pax: number;
  company: Company;
  sent_guide_requests_count: number;
  suggested_in_office_at: Date;
  suggested_out_of_office_at: Date;
  total_cost?: number;
  total_cost_per_guide?: number;
}

export interface AssignedCompanyResource {
  id: number;
  name: string;
  description: null;
  resource_type_id: number;
  company_id: number;
  disabled_at: null;
  created_at: Date;
  updated_at: Date;
  laravel_through_key: number;
}

export interface AssignedGuide {
  id: number;
  company_tour_offer_id: number;
  user_id: number;
  created_at: Date;
  updated_at: Date;
  user: User;
}

export interface Tour {
  id: number;
  company_id: number;
  minutesDuration: number;
  prepMinutes: number;
  cleanupMinutes: number;
  name: string;
  description: null;
  url: null;
  created_at: Date;
  updated_at: Date;
}

// Generated by https://quicktype.io
export interface Pax {
  id: number;
  company_tour_offer_id: number;
  primary_contact_id: number;
  adults: number;
  children: number;
  pickup_location_id: number;
  pickup_at: Date;
  dropoff_location_id: number;
  dropoff_at: null;
  food_preferences: string;
  notes: string;
  cancelled_at: null;
  created_at: Date;
  updated_at: Date;
  total: number;
  pickup_time: string;
  pickup: Pickup;
  primary: Primary;
  foodPreferences: string;
}

export interface Primary {
  id: number;
  name: string;
  surname: string;
  email: string;
  phone: string;
  phoneCountryCode: string;
  created_at: Date;
  updated_at: Date;
}

export interface Pickup {
  location: Location;
  time: string | null;
  minutesAwayFromOffice: number | null;
}
