export interface Resource {
  type: "camera" | "guide" | "van";
  name: string;
  location?: string | null;
  assignedTo: string | null;
}

export interface Pickup {
  location: Location | null;
  time: string | null;
  minutesAwayFromOffice: number | null;
}

export enum LocationType {
  Point = "Point",
}

export interface Location {
  type: LocationType;
  name: string;
  startHere?: boolean;
  endHere?: boolean;
  coordinates?: {
    latitude: GeolocationCoordinates["latitude"];
    longitude: GeolocationCoordinates["longitude"];
  };
  latitude?: GeolocationCoordinates["latitude"];
  longitude?: GeolocationCoordinates["longitude"];
  created_at?: Date;
}

// Generated by https://quicktype.io

export interface Attribute {
  id: number;
  name: string;
  type: string;
  self_assignable: number;
  created_at: Date;
  updated_at: Date;
  pivot: Pivot;
}

export interface Pivot {
  company_tour_id: number;
  attribute_id: number;
}
